spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://configserver:8071
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.anradev: DEBUG