global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'license-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['license-service:8080']
  - job_name: 'organizationservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['organizationservice:8081']