spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
            - /app/config

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"