spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/IdeaProjects/anra-dev/Spring-cloud-test-app/configserver

server:
  port: 8071

#encrypt:
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo


management:
  endpoints:
    web:
      exposure:
        include: "*"